version: "3.4"

services:
  database:
    image: postgres:10.11-alpine
    volumes:
      - "database_data:/var/lib/postgresql/data"

  cache:
    image: memcached:1.5.20-alpine

  api:
    build: ./api
    depends_on:
      - database
      - cache
    volumes:
      - "app_data:/app"
    env_file: ./api/environment-variables.env

  webapp:
    build: ./webapp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "app_data:/app"
      - "certificates_data:/etc/ssl/:ro"
    depends_on:
      - api

  chatbot:
    build: ./chatbot
    depends_on:
      - api

  letsencrypt-certbot:
    image: "certbot/certbot:latest"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "certificates_data:/etc/letsencrypt/"
    command: "certonly -n --standalone -m numerus.textus+letsencrypt@gmail.com --agree-tos --no-eff-email -d numerus-textus.tk -d www.numerus-textus.tk -d api.numerus-textus.tk -d chatbot.numerus-textus.tk"

volumes:
  app_data:
  database_data:
  certificates_data:
